name: adapter
description: Adapter aplikasi Aeronitium
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dotenv: ^2.0.0
  dart_nats: ^0.2.0
  socket_io: ^0.9.4

dev_dependencies:
  pedantic: ^1.9.0
